HRPortal.UI/Controllers/CatagoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRPortal.Data.PolicyRepo;
using HRPortal.Models;
using HRPortal.UI.Models;

namespace HRPortal.UI.Controllers
{
    public class CatagoryController : Controller
    {

        // GET: Catagory
        public ActionResult Index()
        {
            var repo = PolicyRepositoryFactory.CreatePolicyRepository();
            var cats = repo.GetAllCategories();

            return View(cats);
        }

        public ActionResult RequestForm()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RequestFormPost()
        {
            CategoryVM p = new CategoryVM();

            p.Category.CatName = (Request.Form["Category Name"]);

            return View("Result", p);
        }

        public ActionResult ManagePoliciesForDropDown()
        {
            var repo = PolicyRepositoryFactory.CreatePolicyRepository();
            var cats = repo.GetAllCategories();

            PolicyInformationVM pvm = new PolicyInformationVM();

            pvm.Category = new Category();
            pvm.CreateCategoryList(cats);

            return View(pvm);
        }
    }
}

HRPortal.UI/Controllers/PolicyController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRPortal.Data;
using HRPortal.Data.PolicyRepo;
using HRPortal.Models;
using HRPortal.UI.Models;

namespace HRPortal.UI.Controllers
{
    public class PolicyController : Controller
    {
        // GET: Policy
        public ActionResult Index()
        {
            // retrieve all the contacts
            var repo = PolicyRepositoryFactory.CreatePolicyRepository();
            //get policies from repo
            var policies = repo.GetAll();

            return View(policies);
        }

        public ActionResult Edit(int id)
        {
            var repo = PolicyRepositoryFactory.CreatePolicyRepository();
            var pol = repo.GetById(id);

            return View(pol);
        }

        [HttpPost]
        public ActionResult Edit(PolicyInformation policy)
        {
            var repo = PolicyRepositoryFactory.CreatePolicyRepository();
            repo.Edit(policy);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var repo = PolicyRepositoryFactory.CreatePolicyRepository();
            //var pol = repo.GetById(id);
            repo.Delete(id);

            return RedirectToAction("Index");
        }

        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(PolicyInformation model)
        {
           
            var repo = PolicyRepositoryFactory.CreatePolicyRepository();
            // get the Cat ID *********************************
            var catNum = 0;
            if (model.CatName == "Food" || model.CatName == "Attendance")
            {
                catNum = model.CatId;
            }
            
            model.CatName = repo.GetCatById(catNum);

            // add the policy
            repo.Add(model);

            return RedirectToAction("Index");
            //return View(model);
        }

      
    }
}

HRPortal.UI/Views/Catagory/Index.cshtml
@model IEnumerable<HRPortal.Models.Category>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CatId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CatName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CatId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CatName)
        </td>
    </tr>
}

</table>

HRPortal.UI/Views/Catagory/ManagePoliciesForDropDown.cshtml
@model HRPortal.UI.Models.PolicyInformationVM

@{
    ViewBag.Title = "ManagePoliciesForDropDown";
}

<h2>ManagePoliciesForDropDown</h2>

@using (Html.BeginForm("Create", "Policy", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>PolicyInformationVM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.PolId, "ID")
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolicyName, "Policy Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PolicyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PolicyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, "Creation Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreationDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PolicyText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PolicyText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PolicyText, "", new { @class = "text-danger" })
            </div>
        </div>
        <div>
            <p>
                @Html.LabelFor(model => model.Category.CatName, htmlAttributes: new {@class = "control-label col-md-2"})

                @Html.DropDownListFor(m => m.Category.CatName, Model.ListCat, htmlAttributes: new {@class = "control-label col-md-2"})
            </p>
            <hr />
        </div>

        <div>
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

HRPortal.UI/Views/Catagory/RequestForm.cshtml
@model HRPortal.UI.Models.CategoryVM

@{
    ViewBag.Title = "RequestForm";
}

<h2>Category</h2>
@using (Html.BeginForm("RequestFormPost", "Catagory", FormMethod.Post))
{
    <div>
        @Html.DisplayFor(m => m.Category.CatName)
    </div>



    <button class="btn btn-primary">Submit</button>

    @*<div class="form-group">
        <label>Person Id</label>
        <input type="text" name="PersonId" class="form-control" />
    </div>
    <div class="form-group">
        <label>First Name</label>
        <input type="text" name="FirstName" class="form-control" />
    </div>
    <div class="form-group">
        <label>Last Name</label>
        <input type="text" name="LastName" class="form-control" />
    </div>*@
}

HRPortal.UI/Views/Catagory/Result.cshtml
@model HRPortal.UI.Models.CategoryVM

@{
    ViewBag.Title = "Result";
}

<h2>Result</h2>
<p>Name: @Model.Category.CatName</p>